Indicadores Sisab v01
ImpulsoGov/etl pull request #10
Opened 2022-05-05 01:08 UTC by WaltMath

Rotina de ETL referente ao relatório do SIsab sobre os indicadores municipais do Brasil Previne
Inclui:
-  Script de captura dos agendamentos --> impulsoetl.scripts.**impulso_previne.py**
- Módulo de extração --> impulsoetl.sisab.indicadores_municipios.**extracao.py**
- Módulo de tratamento -->   impulsoetl.sisab.indicadores_municipios.**tratamento.py**
- Módulo de validação dos dados-->   impulsoetl.sisab.indicadores_municipios.**teste_validacao.py**
- Módulo de inserção dos dados-->   impulsoetl.sisab.indicadores_municipios.**carregamento.py**
- Arquivo de definição de tabelas de destino-->   impulsoetl.sisab.indicadores_municipios.**modelos.py**
- Arquivo principal-->   impulsoetl.sisab.indicadores_municipios.**principal.py**

2022-05-18 15:33 UTC, bcbernardo requested changes
Revisão finalizada, @WaltMath. Tirando o commit dos dados carregados no lugar incorreto (arquivo `carregamento.py`) e a necessidade de reverter o hack do `__init__.py` (e a sintaxe de importação correspondendo no `scripts/impulso_previne.py`), o resto é perfumaria.

2022-05-18 15:33 UTC, bcbernardo commented on src/impulsoetl/sisab/indicadores_municipios/carregamento.py
> +    conector.execute(requisicao_insercao)
Descobri recentemente que não precisa fazer os dois passos. Só a linha `sessao.execute(requisicao_insercao)` já funcionaria.

2022-05-18 15:33 UTC, bcbernardo commented on src/impulsoetl/sisab/indicadores_municipios/carregamento.py
> +        tabela_nome=f"dados_publicos.sisab_indicadores_municipios_{sufixo_tabela}",
Preferir a sintaxe `"dados_publicos.sisab_indicadores_municipios_{}".format(sufixo_tabela)` ao uso de f-strings.

2022-05-18 15:33 UTC, bcbernardo commented on src/impulsoetl/sisab/indicadores_municipios/principal.py
> +                sessao.commit()
Remover esse bloco. Fazer commit das alterações aqui não é necessário - na verdade, nem desejável, porque levaria a commits só com parte dados em caso de falha do ETL de algum dos 7 indicadores.

2022-05-20 15:04 UTC, WaltMath commented
@bcbernardo correções aplicadas

2022-05-24 18:37 UTC, bcbernardo reviewed
Aprovado. Pendente de rodar formatadores (@bcbernardo).

2022-05-24 21:23 UTC, bcbernardo approved these changes

2022-05-24 22:11 UTC, merged