Adiciona ETL para tabela de habilitações do SCNES
ImpulsoGov/etl pull request #37
Opened 2022-08-29 13:08 UTC by biacunha

2022-08-29 15:14 UTC, bcbernardo requested changes
Alguns poucos comentários nos arquivos.

*Além deles*  deletar o arquivo `tests/.DS_Store` e adicionar uma linha com `.DS_Store` no final do arquivo `.gitignore` (presente na raiz do repositório).

2022-08-29 15:14 UTC, bcbernardo commented on src/impulsoetl/scripts/geral.py
> +def habilitacoes_disseminacao(
Adicionar chamada à função `habilitacoes_disseminacao()` dentro da função `principal()` deste arquivo (ao redor da linha 140).

2022-08-29 15:14 UTC, bcbernardo commented on src/impulsoetl/scripts/geral.py
> +        "Capturando vínculos profissionais do SCNES.",
Corrigir log para mencionar habilitações.

2022-08-29 15:14 UTC, bcbernardo commented on tests/scnes/teste_habilitacoes.py
> +    return pd.read_parquet("CNES_HBSE2111_.parquet")
O caminho do arquivo aqui deveria ser `tests/scnes/CNES_HBSE2111_.parquet`... curioso ter funcionado o teste assim mesmo :thinking:

2022-08-29 15:14 UTC, bcbernardo commented on tests/scnes/teste_habilitacoes.py
> +    return pd.read_parquet("habilitacoes_transformado.parquet")
Idem acima. Teoricamente, o caminho do arquivo seria `tests/scnes/habilitacoes_transformada.parquet`

2022-08-29 15:14 UTC, bcbernardo commented on tests/scnes/teste_habilitacoes.py
> +            "Coluna no De-Para não existe no arquivo de procedimentos: "
Corrigir mensagem para "...não existe no arquivo de habilitações"

2022-08-29 15:14 UTC, bcbernardo commented on tests/scnes/teste_habilitacoes.py
> +            "Coluna existente no arquivo de procedimentos não encontrada no "
Corrigir mensagem para "Coluna inexistente no arquivo de habilitações..."

2022-08-29 15:16 UTC, biacunha commented on tests/scnes/teste_habilitacoes.py
> +    return pd.read_parquet("habilitacoes_transformado.parquet")
Então, eu tive que mudar pra funcionar... até esqueci de te perguntar. Será que vai dar problema?

2022-09-01 17:35 UTC, bcbernardo approved these changes

2022-09-01 17:38 UTC, bcbernardo commented
Pendente apenas a remoção do arquivo `tests/.DS_Store` e inclusão dele no `.gitignore` para incorporar ao repositório.

2022-09-05 16:54 UTC, merged